### PR TITLE
fix(converters): whitelist xhttp mode so one junk value cannot sink the whole clash.yaml

### PR DESCRIPTION
**Pull request by mmdverse**
## What does this change?

`_clash_transport_opts` no longer writes an xhttp `mode` verbatim. The value is
normalized and checked against the modes mihomo actually implements; anything else is
left out of the output while the node itself stays in the document.

## Why?

mihomo rejects the whole configuration file at load time when it meets an xhttp mode it
does not implement, not just the offending proxy:

```text
level=error msg="proxy 11619: xhttp mode gun is not implemented yet"
configuration file /tmp/r.yaml test failed
```

That is the vmess `scy` incident from #17 again: one node out of 11,621 made
`all/clash.yaml` unusable, and because the failure hits the validation gate instead of
the publish step, the round stops and the next one reads the same node — a frozen `main`.

Today's corpus does not trip it. All 422 xhttp nodes carry either no `mode` or one of
`auto`, `stream-up`, `stream-one`, `packet-up`, so this is a latent landmine: the first
upstream that emits `mode=gun`, `mode=multi`, `mode=AUTO` or a padded value freezes the
publish.

## What did you measure?

Pinned CI binaries, sha256 verified, one proxy per document:

```text
mihomo v1.19.29
  mode absent / auto / packet-up / stream-up / stream-one   -> rc=0
  mode gun / multi / AUTO / " packet-up " / foo             -> rc=1
      level=error msg="proxy 0: xhttp mode <m> is not implemented yet"

offline repro on all/configs.txt (12,128 lines -> 12,121 kept):
  baseline                     mihomo -t rc=0
  + one node with mode=gun     mihomo -t rc=1 (whole 4.7 MB document rejected)
  after the change             mihomo -t rc=0, node still published, mode omitted

suite: 457/457 before -> 461/461 after (4 new tests, the first fails on the base commit)
```

## Checklist

- [x] Branched from `main`, and this PR is **one logical change**.
- [x] **No regenerated output files in the diff.**
- [x] Commit messages follow Conventional Commits.
- [x] No commit subject contains `[auto-output]`.
- [x] Behaviour changes come with a test — the first one fails before the change.
- [x] Nothing is advertised that the code does not actually deliver.

### CODE REVIEW

**Review by 0xRadikal — APPROVED** [review]
Thank you for this — it is a genuinely good catch, and the write-up made it
straightforward to verify. I reproduced every claim independently before
approving; notes below so the evidence is on the record.

## The bug is real, and I confirmed it from upstream source

`scripts/converters.py` on `main` writes the value through unchecked:

```python
if p.get("mode"):
    xh["mode"] = p["mode"]
```

I pulled the pinned client's own source rather than relying on the error
message. `MetaCubeX/mihomo` **v1.19.29** — which is exactly what
`aggregate.yml` installs (`MIHOMO_VERSION: "v1.19.29"`):

`transport/xhttp/client.go`
```go
mode := cfg.EffectiveMode(hasReality)
switch mode {
case "stream-one", "stream-up", "packet-up":
    ...
default:
    return nil, fmt.Errorf("xhttp mode %s is not implemented yet", mode)
}
```

`transport/xhttp/config.go`
```go
func (c *Config) NormalizedMode() string {
    if c.Mode == "" { return "auto" }
    return c.Mode            // no strings.ToLower anywhere
}
func (c *Config) EffectiveMode(hasReality bool) string {
    mode := c.NormalizedMode()
    if mode != "auto" { return mode }
    ...
}
```

This settles the two points your whitelist depends on:

- the comparison really is **case-sensitive**, so `AUTO` would be rejected and
  your `strip().lower()` normalization is load-bearing rather than cosmetic;
- `""` and `auto` are both safe, because `EffectiveMode` expands them to a
  concrete implemented mode before the `switch`.

So `{auto, packet-up, stream-up, stream-one}` is both **complete** (it covers
every concrete mode upstream implements) and **minimal** (the only addition
beyond the switch is `auto`, which upstream itself expands).

## The blast radius is as bad as you describe

`scripts/validate.py` runs `mihomo -t -d <dir> -f <file>` and `--strict` makes
a failure exit non-zero. That gate runs **before** the publish step, so one bad
node aborts the round, nothing is published, and the next round re-reads the
same upstream node. That is a self-sustaining freeze, not a one-off skip — the
same shape as the vmess `scy` incident in #17.

I confirmed the emission on `main`'s code directly: `mode=gun` is written into
`all/clash.yaml` verbatim.

## Latent today — which your description states accurately

Independent count over the currently published `all/configs.txt` (11,991 lines,
405 xhttp nodes):

```
auto: 297   stream-one: 28   stream-up: 22   packet-up: 17   (absent): 41
offenders: 0
```

Nothing trips it right now, so this is a landmine rather than an outage. I
appreciate that the PR says so plainly instead of overstating the urgency.

## Test results

Measured on a complete checkout, three states:

| state | result |
|---|---|
| `main` code + `main` tests | **457/457** |
| `main` code + **your** tests | **457/461** — all 4 new tests fail |
| your code + your tests | **461/461** |

The middle row is the one that matters: the new tests genuinely detect the bug
rather than passing alongside a no-op. On `main`'s code they fail as:

```
❌ test_xhttp_unimplemented_mode_cannot_burn_the_whole_clash_document
       {'path': '/x', 'mode': 'gun'}
💥 test_xhttp_mode_is_normalized_before_the_whitelist
       AttributeError: module 'converters' has no attribute 'XHTTP_MODES'
💥 test_every_implemented_xhttp_mode_still_reaches_the_clash_document
💥 test_no_emitted_clash_proxy_advertises_an_unimplemented_xhttp_mode
```

+4 tests, +4 passes, zero regressions, and the passing count stays exactly 457,
so nothing else was disturbed.

## Robustness beyond what the PR claims

I pushed ~40 additional inputs through `_clash_transport_opts`, including a NUL
byte, a 5,000-character value, a YAML-injection attempt (`auto\nmode: gun`), a
Cyrillic homoglyph (`auто`), an RTL override, `${jndi:...}`, path traversal, and
the non-string types `None / 0 / 1 / True / False / [] / {} / b"auto" / 3.14 /
object()`. In every case the emitted `mode` was either absent or a member of the
whitelist, and nothing raised. The `isinstance(raw, str)` guard is what makes
the non-string cases safe.

Also verified: valid modes still reach the document unchanged; `AUTO` and
`" packet-up "` are normalized and **rescued** rather than dropped; every node
survives (6 in, 6 out), matching the project's existing "drop the bad value,
keep the node" policy; and `ws` / `grpc` / `h2` / `http` / `tcp` /
`httpupgrade` output is byte-identical.

## Style and scope

`ruff check scripts/` passes. The new helper mirrors the three sanitizers
already in the file — `(raw: Any) -> str`, a `frozenset` whitelist, `""` on
rejection — and it is applied on the only code path that constructs
`xhttp-opts`. The sing-box path is untouched, which is right, since it drops
xhttp already.

**Approving.** One mechanical step is needed before it can land — see the
comment below.

**Comment by 0xRadikal** [comment]
One mechanical blocker before this can merge: GitHub currently reports this PR
as `mergeable_state=dirty`.

The cause is not your change. The branch carries an inherited commit from
before your own:

| commit | author | files |
|---|---|---|
| `0bce16a` | `raydikalx-bot[actions]` | 91 — a published-output snapshot |
| `d6ab510` | **you** | 2 — `scripts/converters.py`, `scripts/test_pipeline.py` |

`main` republishes that generated output roughly every 15 minutes, so those 91
files have since moved on both sides and now collide. Your own commit is clean:
comparing its tree against its parent gives 181 files before, 181 after, nothing
added or removed, and exactly two paths differing — the two source files.

Dropping that inherited commit clears the conflict. A plain `git rebase
upstream/main` will **not** work — I tried it on a replica of this branch's
topology and it stops on `all/configs.txt` and `heavy/configs.txt`. Replaying
only your own commit avoids the generated files entirely:

```bash
git remote add upstream https://github.com/0xRadikal/Free-v2ray-Configs.git   # if needed
git fetch upstream main

# replay ONLY your commit onto current main, dropping the inherited snapshot
git rebase --onto upstream/main HEAD~1 HEAD

git push --force-with-lease
```

I verified this on a replica: it completes with no conflict, leaves exactly one
commit above `main`, changes only the two source files, keeps `main`'s newer
published output intact, and preserves you as the commit author.

Equivalent alternative if you prefer a fresh branch:

```bash
git fetch upstream main
git checkout -b fix/xhttp-mode-whitelist-v2 upstream/main
git cherry-pick d6ab510ac7c9106de4bb803a730f5f59e9fe34f1
git push -u origin fix/xhttp-mode-whitelist-v2
```

Please don't `git reset --hard upstream/main` — that discards the fix.

Once the PR shows as mergeable I will merge **this** PR, so the commit lands
under your authorship and counts as your contribution. I would rather wait for
your rebase than reopen the same change under my own name.

If you would prefer I handle the rebase myself, say so and I will push it to
your branch — `maintainer_can_modify` is enabled, but I won't touch your branch
without your go-ahead.

**Comment by 0xRadikal** [comment]
Landed as 089a8fa — and the commit is **authored by you**, not by me:

```
commit 089a8fa
Author:    mmdverse <102325921+mmdverse@users.noreply.github.com>
Committer: 0xRadikal <64886141+0xRadikal@users.noreply.github.com>
```

GitHub attributes it to your account, so it appears in your contribution graph
and in `git log` / `git blame`. There is a `Co-authored-by` trailer as well.

### Why it went through #23 instead of this PR

This branch was cut from a commit that already carried a published-output
snapshot, so it held two commits — an inherited `[auto-output]` snapshot of 91
generated files (authored by the repo's own bot), and your own 2-file fix.
`main` republishes that generated output roughly every 15 minutes, so those 91
files moved on both sides and left this PR at `mergeable_state=dirty`.

Rebasing your branch would have cleared it, but you were away from your machine,
and pushing to your fork from here is not possible: `maintainer_can_modify` is
enabled, yet both `POST /git/blobs` and `git push` against your fork are
rejected with `permission denied` (that flag only grants the write to GitHub's
own UI, not to an API token). Rather than sit on the fix or rewrite it, we
carried it over with your permission.

Your two blobs were reused **byte-for-byte** — the blob object IDs on `main` are
identical to the ones on this branch, `4c3fcd7` and `d029131`, so not a single
character was altered. #23 was merged with **rebase** specifically because I
measured that squash rewrites the author to the merger, which would have erased
your name; rebase preserves it.

### What was verified before landing

- Your claims checked against the pinned client's own source, `MetaCubeX/mihomo`
  v1.19.29: `transport/xhttp/client.go` accepts only `stream-one` / `stream-up`
  / `packet-up`, and `transport/xhttp/config.go` maps `""` to `auto` with no
  lowercasing — so your whitelist is complete and minimal, and the
  `strip().lower()` normalization is load-bearing.
- Tests on the exact post-merge tree: **457/457 → 461/461**. With only your four
  tests applied to the unfixed converter the suite reports **457/461**, so they
  genuinely detect the bug.
- 405 xhttp nodes in the live corpus, zero currently carrying an unimplemented
  mode — the latent case is now closed before it could fire.
- ~40 hostile inputs (NUL byte, 5,000-character value, YAML injection, Cyrillic
  homoglyph, RTL override, `${jndi:...}`, path traversal, non-string types):
  the emitted `mode` was always absent or whitelisted, and nothing raised.
- `ruff check scripts/` passes; only the two source files changed on `main`;
  every published output byte-identical.

Thank you — this was a careful piece of work, and the write-up made verifying it
straightforward. Closing this PR as landed via #23, not as rejected.

**Comment by mmdverse** [comment]
Thanks — you went further than the PR needed: checking it against mihomo's own source, the hostile-input pass, and rebase over squash so authorship holds. It came through clean on my end.

Nothing else from me on this one. If the same class turns up again (`scy` in #17, `mode` here — one node value taking the whole file down), I'll branch straight off current main and skip the inherited snapshot.
